language: rust
sudo: requred
dist: trusty
addons:
  apt:
    packages:
      - build-essential
      - php5-curl
      - make
      - libssl-dev
      - g++
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux

env:
  - RUSTFLAGS="-C target-feature=-crt-static"

before_script: |
  curl https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
  source ~/.profile
  curl https://www.openssl.org/source/openssl-1.0.2l.tar.gz | tar xz && cd openssl-1.0.2l && ./config && make && sudo make install
  sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
  wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.2.2/openapi-generator-cli-4.2.2.jar -O openapi-generator-cli.jar
  mkdir -p ~/bin/openapitools
  curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ~/bin/openapitools/openapi-generator-cli
  chmod u+x ~/bin/openapitools/openapi-generator-cli
  export PATH=$PATH:~/bin/openapitools/

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - ~/bin/openapitools/openapi-generator-cli generate -i enigma/openapi/spec/enigma.yaml -g rust-server -o enigmaservice/ --package-name enigmaservice
  - cargo clean
  - cargo build
  - cargo test --manifest-path=Cargo.toml
  - cargo test --release --manifest-path=Cargo.toml

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  fast_finish: true
  email: false
