FROM openapitools/openapi-generator-cli

ARG USER

RUN adduser -u 1000 -G users -h /home/$USER -s /bin/sh -D $USER
USER $USER

WORKDIR /local

COPY enigma/openapi/spec/enigma.yaml /

CMD ["generate", "-i", "/enigma.yaml", "-g", "rust-server", "-o", "/local/enigmaservice/", "--package-name", "enigmaservice"]
