FROM openapitools/openapi-generator-cli AS openapi-builder

RUN mkdir /openapi
COPY enigma/openapi /openapi

WORKDIR /local

# will be generated by yeoman
RUN /usr/local/bin/docker-entrypoint.sh generate -i /openapi/spec/enigma.yaml -g rust-server -o /local/enigmaservice/ --package-name enigmaservice

FROM rust:1.45-alpine3.12 AS rust-builder

WORKDIR /workspace_enigma

# will be generated by yeoman
COPY --from=openapi-builder /local/enigmaservice /workspace_enigma/enigmaservice

RUN apk update

RUN apk add g++ openssl-dev
ENV RUSTFLAGS "-C target-feature=-crt-static"

COPY . .

RUN cargo build -p enigma

FROM alpine:3.12

RUN apk update
RUN apk add ca-certificates gcc openssl

WORKDIR /enigma

COPY --from=rust-builder /workspace_enigma/target/debug/enigma /enigma/
COPY --from=rust-builder /workspace_enigma/enigma/server-* /enigma/

CMD ["./enigma"]
EXPOSE 3000
