FROM openapitools/openapi-generator-cli AS openapi-builder

RUN mkdir /openapi
COPY enigma/openapi /openapi

WORKDIR /local

# will be generated by yeoman
RUN /usr/local/bin/docker-entrypoint.sh generate -i /openapi/spec/enigma.yaml -g rust-server -o /local/enigmaservice/ --package-name enigmaservice

FROM rust:1.40-alpine3.10 AS rust-builder

WORKDIR /workspace_enigma

# will be generated by yeoman
COPY --from=openapi-builder /local/enigmaservice /workspace_enigma/enigmaservice

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/main' >> /etc/apk/repositories
RUN apk update

RUN apk add g++ openssl-dev=1.0.2u-r0
ENV RUSTFLAGS "-C target-feature=-crt-static"

COPY . .

RUN cargo build -p enigma

FROM alpine:3.10

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/main' >> /etc/apk/repositories
RUN apk update
RUN apk add ca-certificates gcc openssl=1.0.2u-r0

WORKDIR /enigma

COPY --from=rust-builder /workspace_enigma/target/debug/enigma /enigma/
COPY --from=rust-builder /workspace_enigma/enigma/server-* /enigma/

CMD ["./enigma"]
EXPOSE 3000
