FROM openapitools/openapi-generator-cli

ARG USER
ARG HOME=/home/$USER

RUN adduser -u 1000 -G users -h $HOME -s /bin/sh -D $USER
USER $USER

WORKDIR $HOME

COPY enigma/openapi/spec/enigma.yaml /

CMD ["generate", "-i", "/enigma.yaml", "-g", "rust-server", "--package-name", "enigmaservice"]
